CREATE TABLE posts (
    post_id INT AUTO_INCREMENT PRIMARY KEY,
    id INT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE
);